allow deriving `CheckedBitPattern` for enums with fields
Lokathor/bytemuck pull request #171
Opened 2023-02-08 10:19 UTC by Freax13

This pr consist of two parts:
1. Miscellaneous improvements to the internal `Representation` type
2. The implementation for deriving `CheckedBitPattern` for enums with fields

The following representations have a stable type layout for enums with fields and are now supported in the `CheckedBitPattern` derive macro:
- `#[repr(C)]`
- `#[repr(C, int)]`
- `#[repr(int)]`
- `#[repr(transparent)]`

The representations are specified at https://doc.rust-lang.org/reference/type-layout.html.

Closes #166

2023-02-10 13:15 UTC, fu5ha commented
Thanks for the PR! Just noting it will probably take me a while longer to get around to reviewing it, sorry about that!

2023-09-05 21:48 UTC, Freax13 commented
Ping @fu5ha @Lokathor

2023-09-05 21:55 UTC, Freax13 commented
I just rebased this onto the latest main branch.

2023-09-05 23:06 UTC, Lokathor commented
I gave fusha a poke on discord and she said she'd try to get to this soon.

2023-09-06 14:28 UTC, fu5ha requested changes
Thanks for the patience on my review. Nice work! Hope you don't mind I took the liberty of changing some variable names and adding some comments to the new derives as I went through and tried to verify them. As far as I can tell it all checks out :)

Could you update the doc comment on the checked bit pattern proc macro derive fn in the derive crate `lib.rs` to reflect the new capabilities and restrictions on enums with fields? Other than that, I think this seems ready to merge.

2023-09-06 14:57 UTC, Freax13 commented
> Thanks for the patience on my review. Nice work! Hope you don't mind I took the liberty of changing some variable names and adding some comments to the new derives as I went through and tried to verify them. As far as I can tell it all checks out :)

Sure, thanks, your changes look good to me.

> Could you update the doc comment on the checked bit pattern proc macro derive fn in the derive crate `lib.rs` to reflect the new capabilities and restrictions on enums with fields? Other than that, I think this seems ready to merge.

Done. I noticed that the description was already out of date even before this pr, so I also updated the parts no related to enums.

2023-09-06 15:32 UTC, fu5ha approved these changes
Awesome. Added another test for a more advanced case. LGTM now!

:shipit: :D

2023-09-06 15:37 UTC, merged

2024-03-10 15:45 UTC, Freax13 commented
@Lokathor Could please you create a new release for bytemuck_derive? Thanks!

2024-03-10 17:43 UTC, Lokathor commented
Ahhhh, sorry about that. Next time definitely don't feel bad about pinging me sooner if you need to.

`bytemuck_derive-1.6.0` is out now!